---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.13.4-alpine
    commands:
      - CGO_ENABLED=0 go test -mod=vendor ./...

  - name: build
    image: golang:1.13.4-alpine
    commands:
      - rm -rf release
      - sh .drone_build.sh

  - name: publish_to_docker
    image: plugins/docker
    settings:
      repo: dhoelle/redactr
      dockerfile: cmd/redactr/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: [push, tag]

  - name: publish_github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - release/drone_*.tar.gz
        - release/drone_checksums.txt
    when:
      event: tag
