---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -mod=vendor ./...

- name: build
  image: golang:1.12
  commands:
  - "(cd cmd/redactr && go build main.go)"
  environment:
    GOFLAGS: -mod=vendor
  when:
    branch:
    - master
    - staging
    - release
    event:
    - push
    status:
    - success

- name: release
  image: golang:1.12
  commands:
  - curl -sL https://git.io/goreleaser | bash
  when:
    event:
    - tag

...
