---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -mod=vendor ./...

- name: fetch
  image: docker:git
  commands:
  - git fetch --tags
  when:
    event:
    - tag

- name: release
  image: goreleaser/goreleaser
  commands:
  - /bin/goreleaser release
  environment:
    GITHUB_TOKEN: "${GITHUB_TOKEN}"
  when:
    event:
    - tag

...
