---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -mod=vendor ./...

- name: fetch
  image: docker:git
  commands:
  - git fetch --tags
  when:
    event:
    - tag

- name: release
  image: goreleaser/goreleaser:v0.106
  commands:
  - /bin/goreleaser release
  environment:
    GITHUB_TOKEN: 
      from_secret: GITHUB_TOKEN
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_REGISTRY:
      from_secret: DOCKER_REGISTRY
  when:
    event:
    - tag

...
