# Drone CI configuration. See http://readme.drone.io/
kind: pipeline
name: default

steps:
  - clone:
      image: plugins/git
      tags: true

  - test:
      image: golang:1.12
      commands:
        - go test -mod=vendor ./...

  - build:
      image: golang:1.12
      commands:
        - (cd cmd/redactr && go build main.go)
      environment:
        - GOFLAGS=-mod=vendor
      when:
        status: success
        branch:
          - master
          - staging
          - release
        event: push

  - release:
      image: goreleaser/goreleaser
      secrets: [github_token]
      commands:
        release
      environment:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      when:
        event: tag
