# goreleaser configuration (http://goreleaser.com)
builds:
- binary: redactr
  main: ./cmd/redactr/main.go
  env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - redactr
    image_templates:
    - "dhoelle/redactr:latest"
    - "dhoelle/redactr:{{ .Tag }}"
    - "dhoelle/redactr:v{{ .Major }}"
    - "dhoelle/redactr:v{{ .Major }}{{ .Minor }}"
    dockerfile: cmd/redactr/Dockerfile