# goreleaser configuration (http://goreleaser.com)
builds:
- binary: redactr
  main: ./cmd/redactr/main.go
  env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  repo: dhoelle/homebrew-formulae