exclude: vendor\/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: trailing-whitespace
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.3
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: golangci-lint